sudo: required
services:
  - docker

before_install:
  - docker build -t kgleeson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kgleeson/react-test npm test 

after_success:
  - docker build -t kgleeson/multi-client ./client  
  - docker build -t kgleeson/multi-nginx ./nginx
  - docker build -t kgleeson/multi-server ./server    
  - docker build -t kgleeson/multi-worker ./worker  
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSSWORD
  - docker push kgleeson/multi-client
  - docker push kgleeson/multi-nginx 
  - docker push kgleeson/multi-server
  - docker push kgleeson/multi-worker