sudo: required
services:
  - docker

before_install:
  - docker build -t kierangleeson/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kierangleeson/react-test npm test 

after_success:
  - docker build -t kierangleeson/multi-client ./client  
  - docker build -t kierangleeson/multi-nginx ./nginx
  - docker build -t kierangleeson/multi-server ./server    
  - docker build -t kierangleeson/multi-worker ./worker  
  - echo "$DOCKER_PASSSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kierangleeson/multi-client
  - docker push kierangleeson/multi-nginx 
  - docker push kierangleeson/multi-server
  - docker push kierangleeson/multi-worker